language:
  - php
  - c

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb
  - memcached

before_install:
 - ./unit-tests/ci/install_prereqs.sh
 - ./unit-tests/ci/setup_dbs.sh

install:
 - composer --prefer-source install

before_script:
 - sudo apt-get -qq install gdb
 - git submodule --quiet update --init --recursive
 - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -Werror -Wno-error=uninitialized"; phpize && ./configure --silent --enable-phalcon && make --silent -j4 > /dev/null && sudo make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini)
 - ulimit -c unlimited || true

script:
 - ZEND_DONT_UNLOAD_MODULES=1 cat script.gdb | sudo gdb --args $(phpenv which php) ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml
 - ZEND_DONT_UNLOAD_MODULES=1 PHALCON_NO_RVO=1 cat script.gdb | sudo gdb --args $(phpenv which php) ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml

after_failure:
 - ./unit-tests/ci/after_failure.sh

notifications:
  email:
    - woodzu123+travis@gmail.com
